# Generated by Django 3.2.15 on 2022-09-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тачки')),
                ('price', models.CharField(choices=[('N', 'Не продаётся'), ('M', 'По корману'), ('MM', 'Придётся взять в кредит'), ('MMM', 'Не вариант')], default='N', max_length=3, verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Описание+характеристики')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='фото авто')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.category')),
            ],
        ),
    ]
