# Generated by Django 3.2.15 on 2022-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тачки')),
                ('price', models.CharField(choices=[('M', 'По корману'), ('MM', 'Придётся взять в кредит'), ('MMM', 'Не вариант')], default='норм', max_length=3, verbose_name='Цена')),
                ('content', models.TextField(verbose_name='Описание+характеристики')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='фото авто')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
