# Generated by Django 3.2.15 on 2022-09-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='category_id',
            new_name='category',
        ),
    ]
